version: "2.1"

services:

  activemq:
    container_name: activemq
    image: rmohr/activemq:5.14.5-alpine
    ports:
      # ui
      - "8161:8161"
      # amqp
      - "5672:5672"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # mqtt
      - "1883:1883"
      # jms
      - "61616:61616"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  springbootapp:
    image: active-mq/springboot
    container_name: springbootapp
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - activemq
    environment:
      - spring.activemq.broker-url=tcp://activemq:61616
      - spring.activemq.in-memory=false
      - spring.activemq.pool.enabled=false
      - server.port=8081
